name: Node.js Package

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Publish to npm
        if: github.event_name == 'push' && !contains(github.event.head_commit.message, 'Release')
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH}}
