name: Node.js Package

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Get package version
        id: version
        run: echo ::set-output name=version::$(node -pe "require('./package.json').version")

      - name: Publish to npm
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' && github.event.head_commit.message =~ /Release v(.+)/
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH}}
